version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    image: nextjsapp:latest
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@db:5432/web-db
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: "postgres:latest"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: web-db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  redis-data:
  redis-insight-data:
  db-data: