version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@db:5432/myappdb
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myappdb
    volumes:
      - db-data:/var/lib/postgresql/data

  redisinsight:
    image: "redislabs/redisinsight:latest"
    ports:
      - "8001:8001"
    volumes:
      - redis-insight-data:/data

volumes:
  redis-data:
  redis-insight-data:
  db-data:
